"""create stocks_ohlcv table

Revision ID: 48259e2cfe17
Revises: 
Create Date: 2026-07-10 16:33:52.085612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48259e2cfe17'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks_ohlcv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_ticker_date')
    )
    op.create_index(op.f('ix_stocks_ohlcv_date'), 'stocks_ohlcv', ['date'], unique=False)
    op.create_index(op.f('ix_stocks_ohlcv_id'), 'stocks_ohlcv', ['id'], unique=False)
    op.create_index(op.f('ix_stocks_ohlcv_ticker'), 'stocks_ohlcv', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_ohlcv_ticker'), table_name='stocks_ohlcv')
    op.drop_index(op.f('ix_stocks_ohlcv_id'), table_name='stocks_ohlcv')
    op.drop_index(op.f('ix_stocks_ohlcv_date'), table_name='stocks_ohlcv')
    op.drop_table('stocks_ohlcv')
    # ### end Alembic commands ###
